version: '3'
services:
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./exp:/var/www/exp:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    volumes:
     - ./data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: psipsi
      MYSQL_DATABASE: participants
      MYSQL_USER: psiturk
      MYSQL_PASSWORD: psiturk

  psiturk:
    build: .
    volumes:
     - ./exp:/psiturk
    tty: true
    stdin_open: true
    restart: always

  adminer:
    image: adminer:latest
    ports:
      - 127.0.0.1:8080:8080
