# Dockerfile for running eficient-Learning-Khan analyses
# Use Dockerfile-experiment to build an environment for running the experiment
FROM debian:stretch
MAINTAINER Paxton Fitzpatrick <paxton.c.fitzpatrick@dartmouth.edu>

# install some basic stuff on top of minbase debian
RUN apt-get update --fix-missing && apt-get install -y eatmydata
RUN eatmydata apt-get install -y \
    wget \
    bzip2 \
    ca-certificates \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    libfreetype6-dev \
    swig \
    mpich \
    pkg-config \
    gcc \
    procps \
    git \
    curl \
    vim

# force "apt-get update" to happen in later intermediates
RUN rm -rf /var/lib/apt/lists/*

# install anaconda (Python=3.7)
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.continuum.io/archive/Anaconda3-2019.10-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && \
    rm ~/anaconda.sh

# set conda path
ENV PATH /opt/conda/bin:$PATH

# enable UTF-8 locale
ENV LANG C.UTF-8

# make remaining commands happen inside the environment
# SHELL ["conda", "run", "-n", "base", "/bin/bash", "-c"]


# update setuptools
RUN conda update setuptools

# install jupyterlab
RUN conda install -c conda-forge jupyterlab

# Install proper package versions
# pip install to avoid slow conda compatibility checks
RUN pip install \
    numpy==1.16.5 \
    scipy==1.2.1 \
    pandas==0.25.2 \
    nltk==3.4.5 \
    matplotlib==3.1.0 \
    seaborn==0.9.0 \
    scikit-learn==0.21.3 \
    spurplus==2.3.3 \
    hypertools==0.6.2 \
    git+git://github.com/lmcinnes/umap.git@fc59aa78f14b10e5eafc19b18fc135de1c5382ea#egg=umap_learn

# expose a port to run jupyter notebooks
EXPOSE 22364